apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

resources:
  - namespace.yml


helmCharts:
- name: signoz
  repo: https://charts.signoz.io
  releaseName: signoz-obs
  namespace: observability
  valuesFile: values.yml
  includeCRDs: true